name: Build PowerSave

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-powersave.yml"
      - ".github/workflows/build-kernel.yml"
      - "scripts/powersave_defconfig.patch"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      mode: PowerSave
